version: '2'
services:
  postgres:
    image: postgres:latest
    environment:
     - POSTGRES_PASSWORD=mysecretpassword
    ports:
     - "5432:5432"
  node-people-api:
    image: stevenalexander/node-people-api:latest
    environment:
     - POSTGRES_PASSWORD=mysecretpassword
     - POSTGRES_HOST=postgres
    links:
     - postgres
    depends_on:
     - postgres
  node-people-web:
    build: .
    ports:
     - "3000:3000"
    environment:
     - API_URL=http://node-people-api:3001/people/
    links:
     - node-people-api
    depends_on:
     - node-people-api